### ISSUE TITLE
Create classic FizzBuzz solution

### ISSUE THREAD

**Issue by EStog** [EStog/fizzbuzz#1]
The problem description is the following (adapted from https://wiki.c2.com/?FizzBuzzTest):

> "Write a program that generates the numbers from 1 to n. But for
> multiples of three gives “Fizz” instead of the number and for the
> multiples of five gives “Buzz”. For numbers which are multiples of both
> three and five gives “FizzBuzz”."

For example:

```python
>>> list(classic_fizzbuzz(20))
['1', '2', 'Fizz', '4', 'Buzz', 'Fizz', '7', '8', 'Fizz', 'Buzz', '11', 'Fizz', '13', '14', 'FizzBuzz', '16', '17', 'Fizz', '19', 'Buzz']
```

**Comment by EStog** [comment]
Added the following test cases:

```python
>>> list(classic_fizzbuzz(0))
[]
>>> list(classic_fizzbuzz(-1))
[]
>>> try:
...     list(classic_fizzbuzz(object()))
... except TypeError:
...     pass # Right!
... else:
...     print('Wrong!')
```

**Comment by arignack** [comment]
Good use of GitHub as a project management platform.

**Comment by EStog** [comment]
Thank you!
